# Generated by Django 4.1.1 on 2022-10-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetracker',
            name='coin',
            field=models.CharField(choices=[('btc', 'Bitcoin')], max_length=100),
        ),
    ]
