# Generated by Django 4.1.1 on 2022-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0002_alter_pricetracker_coin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetracker',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='pricetracker',
            name='currency',
            field=models.CharField(default='USD', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pricetracker',
            index=models.Index(fields=['timestamp'], name='price_track_timesta_afe943_idx'),
        ),
    ]
